# Generated by Django 2.0.1 on 2018-02-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_psp', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_title', models.CharField(max_length=100)),
                ('speech', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spearch.Institution')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spearch.Speaker')),
            ],
        ),
    ]
