# Generated by Django 2.1.2 on 2018-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='url_psp',
            field=models.URLField(null=True),
        ),
    ]
